### ISSUE TITLE
Wi-Fi issue

### ISSUE THREAD

**Issue by trsbox** [williamhaley/wifi-testing#1]
Hey Will,

First I am sorry for posting here.  Was trying to figure out how to get ahold of you.

I am at a loss here and wanted to see of you could help me.   I have been all over several forums and can not find a solution to my issue.

I bought one of the wifi dongles you recommended on your webpage (think penguin) and am running ubuntu 17.10.

My Kern.log and syslog files fill up to about 100GB to 300GB within several days.   Looking at the logs it appears that the sub dongle is the cause.  Unpluging the dongle stops the entries into the log file.

Thank you for any help you can give me.

Aaron

Here is a link to a screen shot of my error:

https://drive.google.com/file/d/0BwBYGr3idNuqdUhGTlRzVnFaRmhUdXFGMTNvN1pqVThodzE0/view?usp=drivesdk

**Comment by williamhaley** [comment]
No problem @trsbox. Sorry for my delay responding. I replied on the [original blog post](https://willhaley.com/blog/linux-usb-wifi/#comment-3843640922), so I'm thinking we can move the convo there. I'll close this issue out.
